package(default_visibility = ["//visibility:public"])


exports_files([
    "LICENSE",
    "version.bzl",
])

filegroup(
    name = "distribution",
    srcs = [
        "BUILD",
        "LICENSE",
    ],
    visibility = ["//distro:__pkg__"],
)
